baseURL = "https://os-edu.github.io/"
title = "OS-EDU-SITE"
theme = "temple"
# If not set, it will not appear. Otherwise it will show below your footer links
copyright = "(c) 2020 - 2020 Aos Dabbagh -- All rights reserved."

# Enables Chroma-based syntax highlighting with theme "friendly"
# See https://xyproto.github.io/splash/docs/ for other theme options
pygmentsStyle = "friendly"
# If true, Chroma will highlight GitHub-style code fences in addition to
# highlight shortcodes
pygmentsCodeFences = true

[params]
  # Enables the topmenu, which pulls from categories
  topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "os-site"
  github = "OS-EDU"
  email = "wangfuzheng0814@foxmail.com"
  #gaid = "Your Google Analytics ID"
  #twitter = "twitterID"
  medium = "mediumUsername"
